export const TRANSFER_BUK_STEPS_ENUM = {
  LIST: 0,
  RECIPIENT: 1,
  SUMMARY: 2,
  LIST_PROGRESS: 3,
  LIST_REVIEW: 4,
  LIST_NAME: 5,
  TRANSFER_SUMMARY: 6,
  PAYMENT_PIN: 7,
  PAYMENT_SCHEDULED: 8,
};
