export const ONBOARDING_STEPS = {
  NIN: 0,
  NIN_VERIFICATION: 1,
  BVN: 2,
  BVN_VERIFICATION: 3,
  BUSINESS: 4,
  BUSINESS_CAC_REGISTRATION: 5,
  BUSINESS_CAC_REGISTRATION_VERIFICATION: 6,
  BUSINESS_NON_CAC_REGISTRATION: 7,
  PIN_SETUP: 8,
  PIN_SETUP_VERIFICATION: 9,
  ACCOUNT_SETUP_COMPLETED: 10,
};
